# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.5
  - 3.6

env:
  matrix:
    - DJANGO=1.8 CMS=3.3
    - DJANGO=1.8 CMS=3.4
    - DJANGO=1.9 CMS=3.3
    - DJANGO=1.9 CMS=3.4
    - DJANGO=1.10 CMS=3.3
    - DJANGO=1.10 CMS=3.4
    - DJANGO=1.11 CMS=3.3
    - DJANGO=1.11 CMS=3.4

install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO
  - pip install -q django-cms==$CMS
  - python setup.py -q install

script: 
  - coverage run $(which djangocms-helper) cmsplugin_multipinmap test --cms

after_success: coveralls
