# Generated by creimers on 2022-05-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmsplugin_multipinmap", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Pin",
            name="pin_color",
            field=models.CharField(
                choices=[
                    ("redIcon", "red"),
                    ("redIconBlackBorder", "red (black border)"),
                    ("blueIcon", "blue"),
                    ("greenIcon", "green"),
                    ("yellowIcon", "yellow"),
                    ("yellowIconBlackBorder", "yellow (black border)"),
                    ("grayIcon", "gray"),
                    ("blackIcon", "black"),
                ],
                max_length=50,
            ),
        ),
    ]
